In [1]:
import numpy as np
import random

In [2]:
D = 3 #Number of variables of design
F = .5 #Scale factor
CR = .9 #Crossover Rate
Gmax = 10000 #Number of generations
NP = 6 #Number of population

In [3]:
population = np.random.rand(NP, D).round(2) #Generate a random population array
population

array([[0.95, 0.37, 0.77],
       [0.39, 0.  , 0.33],
       [0.83, 0.17, 0.66],
       [0.99, 0.47, 0.05],
       [0.19, 0.35, 0.36],
       [0.78, 0.64, 0.04]])

In [4]:
copy_population = population.copy()

In [5]:
#Create the function to evaluate the initial population
def f(array):
        return np.column_stack((array, np.sum(array, axis=1)))
    

In [6]:
evaluated_population = f(population)
evaluated_population

array([[0.95, 0.37, 0.77, 2.09],
       [0.39, 0.  , 0.33, 0.72],
       [0.83, 0.17, 0.66, 1.66],
       [0.99, 0.47, 0.05, 1.51],
       [0.19, 0.35, 0.36, 0.9 ],
       [0.78, 0.64, 0.04, 1.46]])

In [7]:
def rand_array_selection(array,exclude_value):
    #Get the len of de population
    index = np.arange(len(array))
    #Exclude the current value to pass r0!=r1!=r2!=i
    index = index[index != exclude_value]
    #Select three index values of the population
    selected_index = np.random.choice(index, size=3, replace=False)
    #Save that values 
    r_collection = array[selected_index]
    return r_collection

In [8]:
u = np.zeros(3)
temp_population = np.zeros(4)
best_solution = np.zeros(3)
best_fitness = 1.9

In [9]:
#g_array = []
generations_array = []

In [10]:
generations_array.append(evaluated_population.copy())

In [11]:
for G in range(Gmax):
    print(f"Generation:{G}")
    arrays_u = np.empty((0, 3))
    temp_population = np.empty((0,4)) 
    for i in range(NP):
        #Select three random individuals
        r_collection = rand_array_selection(population,i)
        #Calculate of differential mutuality
        v = r_collection[0] + F * (r_collection[1] - r_collection[2])
        #Get a random integer
        j_rand = random.randint(0, 6)
        for j in range(D):
            #Get a random number between [0 and D]
            rand_value = random.random()
            if (j == j_rand or rand_value < CR):
                #print(f"Mutación:{i},valor random:{rand_value}, j:{j}, j_rand:{j_rand}")
                #print(f"Vector mutado:{v}")
                #we add to the test individual a value of the mutated vector
                u[j] = v[j]
            else:
               #print(f"Sin mutación:{i},valor random:{rand_value}, j:{j}, j_rand:{j_rand}")
                #we do not add to the test individual a value of the mutated vector
                #we use the data of target vector
               u[j] = population[i][j]

        
        #print(f"Vector prueba:{arrays_u}")      
        arrays_u = np.vstack((arrays_u,u))
        #print(arrays_u[i])

        evaluated_array_u = f(arrays_u)
        #print(evaluated_array_u)
        #print(evaluated_array_u[i][3])

        # Update the best solution
        if evaluated_array_u[i][3] < best_fitness:
            best_solution = arrays_u[i]
            best_fitness = evaluated_array_u[i][3]
        
        #Build the new generation and update de population
        if (evaluated_array_u[i][3]<=evaluated_population[i][3]):
            population[i] = arrays_u[i]  
            evaluated_population[i] = evaluated_array_u[i]
            #g_array.append(evaluated_array_u[i])
        else:
            None
            #g_array.append(evaluated_population[i])

    generations_array.append(evaluated_population.copy())
    #Best Solutions
    print(f"Best solution for Gen{G}: {best_solution} and Best fitness: {best_fitness}")  
            
           

Generation:0
Best solution for Gen0: [ 0.295  -0.115   0.4125] and Best fitness: 0.5925
Generation:1
Best solution for Gen1: [ 0.4425  -0.2325   0.35625] and Best fitness: 0.56625
Generation:2
Best solution for Gen2: [ 0.3140625 -0.8215625  0.4125   ] and Best fitness: -0.0950000000000002
Generation:3
Best solution for Gen3: [ 0.3140625 -0.8215625  0.4125   ] and Best fitness: -0.0950000000000002
Generation:4
Best solution for Gen4: [ 0.3140625 -0.8215625  0.4125   ] and Best fitness: -0.0950000000000002
Generation:5
Best solution for Gen5: [ 0.24603516 -0.56979492  0.19664062] and Best fitness: -0.1271191406250001
Generation:6
Best solution for Gen6: [ 0.24603516 -0.56979492  0.19664062] and Best fitness: -0.1271191406250001
Generation:7
Best solution for Gen7: [ 0.26909668 -0.66290466  0.11151855] and Best fitness: -0.28228942871093765
Generation:8
Best solution for Gen8: [ 0.30567139 -0.84309174  0.20731201] and Best fitness: -0.3301083374023438
Generation:9
Best solution for Gen9: 

In [12]:
generations_array = np.array(generations_array) 

In [13]:
generations_array #Generations Array

array([[[ 0.95      ,  0.37      ,  0.77      ,  2.09      ],
        [ 0.39      ,  0.        ,  0.33      ,  0.72      ],
        [ 0.83      ,  0.17      ,  0.66      ,  1.66      ],
        [ 0.99      ,  0.47      ,  0.05      ,  1.51      ],
        [ 0.19      ,  0.35      ,  0.36      ,  0.9       ],
        [ 0.78      ,  0.64      ,  0.04      ,  1.46      ]],

       [[ 0.56      ,  0.555     ,  0.77      ,  1.885     ],
        [ 0.39      ,  0.        ,  0.33      ,  0.72      ],
        [ 0.38      ,  0.58      ,  0.195     ,  1.155     ],
        [ 0.39      ,  0.38      ,  0.2825    ,  1.0525    ],
        [ 0.19      ,  0.35      ,  0.36      ,  0.9       ],
        [ 0.295     , -0.115     ,  0.4125    ,  0.5925    ]],

       [[ 0.4325    ,  0.7275    ,  0.17375   ,  1.33375   ],
        [ 0.39      ,  0.        ,  0.33      ,  0.72      ],
        [ 0.38      ,  0.58      ,  0.195     ,  1.155     ],
        [ 0.4425    , -0.2325    ,  0.35625   ,  0.56625   ],
    

In [14]:
print("Shape of Generations Array:", generations_array.shape)

Shape of Generations Array: (10001, 6, 4)


In [15]:
#g_array = np.array(g_array)
#g_array #Generations Array
#print("Shape of Generations Array:", g_array.shape)

#population
#copy_population
#evaluated_population
#f(copy_population)